name: pharma_sys
description: A pharmacy inventory management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_screenutil: ^5.7.0
  intl: ^0.18.0
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.5
  fl_chart: ^0.71.0
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  sqflite: ^2.2.8+2
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  # flutter_barcode_scanner: ^2.0.0
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  cached_network_image: ^3.2.3
  flutter_slidable: ^3.0.0
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700